#mac version
version: '2'

networks:
    phpeltoken_network:
        ipam:
            driver: default
            config:
                - subnet: 174.18.211.0/24

services:
    nginx:
        container_name: phpeltoken_nginx
        image: nginx:stable
        hostname: phpeltoken.dev
        links:
            - php
        volumes:
            - .:/var/www/phpeltoken.com
            - ./etc/docker/nginx:/etc/nginx/conf.d
        networks:
            phpeltoken_network:
                ipv4_address: 174.18.211.3
        expose:
            - "80"
        ports:
            - "80:80"
    php:
        container_name: phpeltoken_php
        build: ./etc/docker/php
        depends_on:
            - db
            - redis
        links:
            - db
            - redis
        volumes:
            - .:/var/www/phpeltoken.com
            - .:/var/www/phpeltoken.com:cached
        networks:
            phpeltoken_network:
                ipv4_address: 174.18.211.2
        expose:
            - "9000"
        extra_hosts:
            - "postgres.phpeltoken.dev:174.18.211.4"
            - "phpeltoken.dev:174.18.211.3"
        environment:
            # both variables needed to debug command line scripts
            XDEBUG_CONFIG: remote_host=10.254.254.254
            PHP_IDE_CONFIG: "serverName=localhost"
    db:
        container_name: phpeltoken_postgres
        hostname: postgres.phpeltoken.dev
        image: postgres
        environment:
            - DEBUG=false
            - DB_USER=phpeltoken
            - DB_PASS=phpeltoken
            - DB_NAME=phpeltoken
        volumes:
            - ./etc/docker/volume/postgresql:/var/lib/postgresql
        networks:
            phpeltoken_network:
                ipv4_address: 174.18.211.4
        expose:
            - "5432"
        ports:
            - "5432:5432"
    redis:
        container_name: phpeltoken_redis
        hostname: redis.phpeltoken.dev
        image: redis:3.2
        expose:
            - "6379"
        networks:
            phpeltoken_network:
                ipv4_address: 174.18.211.5